#!/usr/bin/env ruby

require_relative 'lib/parse_arguments'

command = ARGV[0]
options = ParseArguments.parse
options[:title] = ARGV[1]
error_messages = ParseArguments.validate(options)

if error_messages.empty?
  puts "Theoretically creating: a movie named #{options[:title]}, with seen? #{options[:seen]}, own? #{options[:own]}, wishlist see #{options[:wishlist_see]}, wishlist own #{options[:wishlist_own]}, rating #{options[:rating]}"
else
  puts error_messages
end